### ISSUE TITLE
Why BigQuery insted of Redshift?

### ISSUE THREAD

**Issue by existeundelta** [Alephbet/gimel#14]
I just read  http://blog.gingerlime.com/2016/a-scalable-analytics-backend-with-google-bigquery-aws-lambda-and-kinesis/ and why  not use Redshift insted of BigQuery?

**Comment by gingerlime** [comment]
No particular reason other than that Redshift costs much more than BigQuery as far as I could tell. With Redshift, you need to set up your own cluster and keep it running. Right? BigQuery charges based on queries and storage.

**Comment by existeundelta** [comment]
ok thanks, I will take a better look

**Comment by gingerlime** [comment]
You're welcome :)
