### ISSUE TITLE
delete experiment (method + HTTP endpoint)

### ISSUE THREAD

**Issue by 314l5926** [Alephbet/gimel#8]
It would be nice to have API methods like "reset experiment" and "delete experiment".

**Comment by gingerlime** [comment]
Yes! it's a good idea. Would be interested contributing to the project? I'm happy to guide you through what needs to be done, but it's definitely doable.

**Comment by 314l5926** [comment]
Well, not sure about the timing, maybe this month I'll do this. 
As I see it, I need to add new methods to the lambda app (gimel.py), and extend WIRING (deploy.py) for API gateway.

Did I miss something?

**Comment by gingerlime** [comment]
That's more or less it, @314l5926.

I'm wondering about the REST verb to use for reset though? Although I guess there's not really a need to reset an experiment - they are created on the fly. So you can just delete it using HTTP DELETE.

**Comment by 314l5926** [comment]
It'll do, agreed.

**Comment by gingerlime** [comment]
included in `v1.1.0`
